name: Bug Report
description: Report a bug in UI5 MCP
type: Bug
body:
  - type: markdown
    attributes:
      value: | 
        Please have a look at our [contributing guidelines](https://github.com/UI5/mcp/blob/main/CONTRIBUTING.md#report-bugs) on reporting issues.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: What is the issue and how can we reproduce it?
      description: |
        To help us understand and resolve the issue efficiently, please provide a **minimal reproducible example** (required) and steps that clearly illustrate the unexpected behavior.
      value: |
        1. Open the sample https:// ...
        2. Click on ...
        3. ... --> **Issue:** ...
        
        #### Error:
        > ...
        
        #### Expected behavior:
        ...
    validations:
      required: true
  - type: input
    id: version-ui5-mcp
    attributes:
      label: Which UI5 MCP version is your project targeting?
      description: Share the UI5 MCP version where the issue occurs.
    validations:
      required: true
  - type: checkboxes
    id: issue-checked
    attributes:
      label: Confirmation
      description: |
        To avoid duplicates and ensure efficient issue resolution, please double-check existing issues.
      options:
        - label: I have searched the existing issues and reviewed the relevant documentation as well as the API reference.
          required: true
        - label: I am not disclosing any internal or sensitive information.
          required: true