name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# No permissions are required for this workflow
permissions: {}

jobs:
  test:
    name: General checks, tests and coverage reporting
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 24
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 24

    - name: Install dependencies
      run: npm ci

    - name: Perform ESLint check
      run: npm run lint

    - name: Perform Licenses check
      run: npm run check-licenses

    - name: Perform dependency check
      run: npm run depcheck

    - name: Perform build
      run: npm run build-test

    - name: Run tests
      run: npm run coverage
